CATEGORIES = {
    'fabric': [
        'beige-fabric',
        'black-fabric',
        'blue-fabric',
        'green-fabric',
        'light-brown-fabric',
        'pink-fabric',
        'pink-fabric2',
        'pink-felt',
        'red-fabric',
        'red-fabric2',
        'white-fabric',
        'white-fabric2',
        'dark-specular-fabric', 
        'acrylic_felt_green',
        'acrylic_felt_orange',
        'acrylic_felt_pink',
        'acrylic_felt_purple',
        'acrylic_felt_white',
        'acrylic_felt_yellow'
    ],    


    'metal': [
        'alum-bronze',
        'aluminium',
        'alumina-oxide',
        'brass',
        'black-oxidized-steel',
        'chrome',
        'chrome-steel',
        'grease-covered-steel',
        'nickel',
        'steel',
        'ss440',
        'tungsten-carbide',
        'two-layer-gold',
        'two-layer-silver', 
        'ilm_solo_m_68'
    ],
    
    'metallic_paint': [
        'blue-metallic-paint',
        'blue-metallic-paint2',
        'gold-metallic-paint',
        'gold-metallic-paint2',
        'gold-metallic-paint3',
        'gold-paint',
        'silver-metallic-paint',
        'silver-metallic-paint2',
        'silver-paint',
        'green-metallic-paint',
        'green-metallic-paint2',
        'red-metallic-paint', 
        'ilm_l3_37_metallic',
        'irid_flake_paint1',
        'irid_flake_paint1_fine',
        'irid_flake_paint2'

        
    ],

    'phenolic': [
        'black-phenolic',
        'red-phenolic',
        'yellow-phenolic',
        'specular-black-phenolic',
        'specular-blue-phenolic',
        'specular-green-phenolic',
        'specular-maroon-phenolic',
        'specular-orange-phenolic',
        'specular-red-phenolic',
        'specular-violet-phenolic',
        'specular-white-phenolic',
        'specular-yellow-phenolic'
    ],
    
    'paint': [
        'color-changing-paint1',
        'color-changing-paint2',
        'color-changing-paint3',
        'dark-blue-paint',
        'dark-red-paint',
        'light-red-paint',
        'orange-paint',
        'purple-paint',
        'yellow-paint',
        'white-paint',
        'pearl-paint', 
        'cg_sunflower',
        'chm_light_blue',
        'chm_mint',
        'chm_orange',
        'cm_military_green',
        'cm_toxic_green',
        'cm_white',
        'colodur_azure_4e',
        'colodur_connemara_4c',
        'colodur_kalahari_2a',
        'colodur_napoli_4f',
        'ilm_l3_37_dark_green',
        'ilm_l3_37_matte',
        'laika_ceiling_paint_18_gray',
        'satin_blue',
        'satin_gold',
        'satin_purple',
        'satin_rosaline',
        'satin_white',
        'vch_dragon_eye_red',
        'vch_frozen_amethyst',
        'vch_golden_yellow',
        'vch_silk_blue',
        'vch_ultra_pink',
        'ilm_solo_millennium_falcon'

    ],
    
    'plastic': [
        'black-soft-plastic',
        'gray-plastic',
        'green-plastic',
        'maroon-plastic',
        'pink-plastic',
        'red-plastic',
        'yellow-plastic',
        'yellow-matte-plastic',
        'red-specular-plastic',
        'delrin',
        'nylon',
        'polyethylene',
        'polyurethane-foam',
        'pvc',
        'teflon', 
        'blue-rubber',
        'neoprene-rubber',
        'pure-rubber',
        'violet-rubber',
        'green-latex', 
        'aurora_white',
        'blue-acrylic',
        'green-acrylic',
        'violet-acrylic',
        'white-acrylic', 
        'aurora_white',
        'cc_ibiza_sunset'

    ],
    
    'wood': [
        'cherry-235',
        'colonial-maple-223',
        'fruitwood-241',
        'ipswich-pine-221',
        'natural-209',
        'pickled-oak-260',
        'special-walnut-224'
    ],
    
    'stone_mineral': [
        'aventurnine',
        'black-obsidian',
        'hematite',
        'pink-jasper',
        'white-marble', 
        'cc_amber_citrine',
        'cc_blue_agat',
        'cc_green_malachite',
        'cc_iris_purple_gem',
        'cc_nothern_aurora'
    ]
}
